const products = [
  {
    id: 1,
    name: "SHIRT MEN 1",
    description: "Ao so mi tay dai mau xam",
    price: 500000,
    priceSlae : 70000,
    imageURL: "images/shirt1.jpg",
    category: "Nam",
    tags: ["noi bat", "sale"],
  },
  {
    id: 2,
    name: "SHIRT MEN 2",
    description: "Ao so mi tay dai mau xanh ",
    price: 500000,
    priceSlae : 70000,
    imageURL: "images/shirt2.jpg",
    category: "Nam",
    tags: ["noi bat", "sale"],
  },
  {
    id: 3,
    name: "SHIRT MEN 3",
    description: "Ao thun soc xanh trang ",
    price: 700000,
    imageURL: "images/shirt3.jpg",
    category: "Nam",
    tags: ["noi bat"],
  },
  {
    id: 4,
    name: "SHIRT WOMAN 4",
    description: "Ao thun trang va so mi xanh ",
    price: 700000,
    imageURL: "images/shirt4.jpg",
    category: "Nam",
  },
  {
    id: 5,
    name: "SHIRT WOMAN 5",
    description: "Do ngu mau hong ",
    price: 300000,
    imageURL: "images/shirt5.jpg",
    category: "Nu",
  },
  {
    id: 6,
    name: "SHIRT WOMAN 6",
    description: "Ao len nu mau hong ",
    price: 700000,
    imageURL: "images/shirt6.jpg",
    category: "Nu",
  },
  {
    id: 7,
    name: "SHIRT WOMAN",
    description: "Ao len nu mau be ",
    price: 700000,
    imageURL: "images/shirt7.jpg",
    category: "Nu",
    tags: ["noi bat"],
  },
  {
    id: 8,
    name: "SHIRT WOMAN 8",
    description: "Do ngu mau den ",
    price: 300000,
    imageURL: "images/shirt8.jpg",
    category: "Nu",
    tags: ["noi bat"],
  },
  {
    id: 9,
    name: "WEATER 9",
    description: "Ao Weater 3 mau ",
    price: 400000,
    imageURL: "images/shirt9.jpg",
    category: "Nam va NU",
    tags: ["noi bat", "sale"],
  },
  {
    id: 10,
    name: "WEATER 10",
    description: "Ao Weater mau den ",
    price: 400000,
    imageURL: "images/shirt10.jpg",
    category: "Nam va NU",
    tags: ["sale"],
  },
  {
    id: 11,
    name: "WEATER 11",
    description: "Ao Weater mau do ",
    price: 400000,
    imageURL: "images/shirt11.jpg",
    category: "Nam va NU",
    tags: ["sale"],
  },
  {
    id: 12,
    name: "WEATER 12",
    description: "Ao Weater mau be ",
    price: 400000,
    imageURL: "images/shirt12.jpg",
    category: "Nam va NU",
    tags: ["sale"],
  },
];
// 

const imagesList = [
    "images/silde-show1.jpg",
    "images/silde-show2.jpg",
    "images/silde-show3.jpg",
]
export {
    products , imagesList
}