const products = [
  {
    id: 1,
    name: "SHIRT MEN 1",
    description: "Ao so mi tay dai mau xam",
    price: 700000,
    priceSale: 500000,
    imageURL: "images/shirt1.jpg",
    category: "Nam",
    tags: ["noi bat", "sale 30%","sale"],
  },
  {
    id: 2,
    name: "SHIRT MEN 2",
    description: "Ao so mi tay dai mau xanh ",
    price: 700000,
    priceSale: 500000,
    imageURL: "images/shirt2.jpg",
    category: "Nam",
    tags: ["noi bat", "sale 30%","sale"],
  },
  {
    id: 3,
    name: "SHIRT MEN 3",
    description: "Ao thun soc xanh trang ",
    price: 700000,
    imageURL: "images/shirt3.jpg",
    category: "Nam",
    tags: ["noi bat"],
  },
  {
    id: 4,
    name: "SHIRT WOMAN 1",
    description: "Ao thun trang va so mi xanh ",
    price: 700000,
    imageURL: "images/shirt4.jpg",
    category: "Nam",
  },
  {
    id: 5,
    name: "SHIRT WOMAN 2",
    description: "Do ngu mau hong ",
    price: 300000,
    imageURL: "images/shirt5.jpg",
    category: "Nu",
  },
  {
    id: 6,
    name: "SHIRT WOMAN 3",
    description: "Ao len nu mau hong ",
    price: 700000,
    imageURL: "images/shirt6.jpg",
    category: "Nu",
  },
  {
    id: 7,
    name: "SHIRT WOMAN 4",
    description: "Ao len nu mau be ",
    price: 700000,
    imageURL: "images/shirt7.jpg",
    category: "Nu",
    tags: ["noi bat"],
  },
  {
    id: 8,
    name: "SHIRT WOMAN 5",
    description: "Do ngu mau den ",
    price: 300000,
    imageURL: "images/shirt8.jpg",
    category: "Nu",
    tags: ["noi bat"],
  },
  {
    id: 9,
    name: "WEATER 1",
    description: "Ao Weater 3 mau ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt9.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat", "sale 40%","sale"],
  },
  {
    id: 10,
    name: "WEATER 2",
    description: "Ao Weater mau den ",
    price: 700000,
    imageURL: "images/shirt10.jpg",
    category: ["Nam", 'Nu'],
    priceSale: 400000,
    tags: ["sale 40%","sale"],
  },
  {
    id: 11,
    name: "WEATER 3",
    description: "Ao Weater mau do ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt11.jpg",
    category: ["Nam", 'Nu'],
    tags: ["sale 40%","sale"],
  },
  {
    id: 12,
    name: "WEATER 4",
    description: "Ao Weater mau be ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt12.jpg",
    category: ["Nam", 'Nu'],
    tags: ["sale 40%","sale"],
  },
  {
    id: 13,
    name: "T SHIRT 1",
    description: "ao thun den",
    price: 400000,
    priceSale: 280000,
    imageURL: "images/shirt13.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat", "sale 30%","sale"],
  },
  {
    id: 14,
    name: "T SHIRT 2",
    description: "ao thun mau hong ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt14.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat", "sale 30%","sale"],
  },
  {
    id: 15,
    name: "T SHIRT 3",
    description: "ao thun den tay ngan ",
    price: 400000,
    priceSale: 280000,
    imageURL: "images/shirt15.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat", "sale 30%","sale"],
  },
  {
    id: 16,
    name: "T SHIRT 4",
    description: "ao thun mau nau",
    price: 400000,
    imageURL: "images/shirt16.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat"],
  },
  {
    id: 17,
    name: "T SHIRT 5",
    description: "ao thun mau trang",
    price: 500000,
    imageURL: "images/shirt17.jpg",
    category: ["Nam", 'Nu'],
    tags: ["noi bat"],
  },
  {
    id: 18,
    name: "T SHIRT 6",
    description: "ao thun mau be ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt18.jpg",
    category: ["Nam", 'Nu'],
    tags: ["sale 40%","sale"],
  },
  {
    id: 19,
    name: "T SHIRT 7",
    description: "ao thun mau hong ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt19.jpg",
    category: ["Nam", 'Nu'],
    tags: ["sale 40%","sale"],
  },
  {
    id: 20,
    name: "T SHIRT 8",
    description: "Ao Weater mau be ",
    price: 700000,
    priceSale: 400000,
    imageURL: "images/shirt20.jpg",
    category: ["Nam", 'Nu'],
    tags: ["sale 40%","sale"],
  },
];
// 

const imagesList = [
  "images/silde-show1.jpg",
  "images/silde-show2.jpg",
  "images/silde-show3.jpg",
]
export {
  products, imagesList
}